### ISSUE TITLE
Share the app folder in Nextcloud

### ISSUE THREAD

**Issue by anmol26s** [YunoHost-Apps/yunohost.multimedia#6]
Hi
Is it possible to share the app folder eg. /var/www/mywebapp/www into the Nextcloud for a user so that its easy to put files in the app folder without changing the app permissions?

**Comment by maniackcrudelis** [comment]
Hi Anmol, I'm not sure to understand the relation between my_webapp and yunohost.multimedia.

**Comment by anmol26s** [comment]
I thought that ynh_media_addfolder.sh could add any folder to the home folder of people. I might have misunderstood.
You can close this if its not related.

**Comment by maniackcrudelis** [comment]
Well, the thing is yes you can use this script to add any directory to the home of an user. But, the directory will be in the multimedia directory, which can be not relevant.

Do you want to do that for a personal usage or for packaging an app ?

**Comment by anmol26s** [comment]
Yes I want to use it for webapp so that www folder should be in the nextcloud and could be managed from there.

**Comment by maniackcrudelis** [comment]
OK, but is it only for your usage ?
Or to add this modification to the package ?

In the first case, you can do that manually.
In the second, you should rewrite the code to adapt it.

**Comment by anmol26s** [comment]
For now its for my personal use. Maybe if someone request in form it could be implemented on this app too.

**Comment by maniackcrudelis** [comment]
In that case, either you do that manually to put the directory where you want, or you can use the script and have your directory in Multimedia.

**Comment by anmol26s** [comment]
But want about the wright and permission? How would they be handled? Symbolic link to the directory to the nextcloud user folder is enough?

**Comment by maniackcrudelis** [comment]
There's a pull request running for allow nextcloud to use Multimedia directories
https://github.com/YunoHost-Apps/nextcloud_ynh/pull/111

But, nextcloud doesn't read symbolic links, so that you'll have to add an external mount in nextcloud.
For permission, nextcloud user has to be added to the multimedia group. https://github.com/YunoHost-Apps/nextcloud_ynh/blob/628cead60fa17dccb8eaf0f0e518e5fa70557e82/scripts/_common.sh#L356-L357

**Comment by anmol26s** [comment]
How to external mount a folder at /etc/www/webapp/www?And where it will be mounted to home/yunohost.app/nextcloud/data/tom/files or /home/tom ? And doing  `usermod -a -G webapp tom` would be enough?

**Comment by maniackcrudelis** [comment]
External mounts are in the admin panel of Nextcloud, you can add any path you want.

And, well if you want to do it manually, first you have to apply these acl permissions
https://github.com/YunoHost-Apps/yunohost.multimedia/blob/master/script/ynh_media_addfolder.sh#L44-L50
And, because it's not a multimedia directory, you can use the group 'nextcloud' instead of 'multimedia'. It's going to give a write permission to nextcloud in your directory.

**Comment by anmol26s** [comment]
Ok I have mounted the location /var/www/my_webapp/www to the nextcloud. I can view the folder but don't have write permission to it.
So now doing  `usermod -a -G nextcloud webapp` should be ok?

**Comment by maniackcrudelis** [comment]
Did you follow the indication above ?
Did you add the ACL permissions ?

**Comment by anmol26s** [comment]
Yes I did this:
```
sudo setfacl -RnL -m g:nextcloud:rwX,g::rwX,o:r-X /var/www/my_webapp/www
sudo setfacl -RnL -m d:g:nextcloud:rwX,g::rwX,o:r-X  /var/www/my_webapp/www
sudo setfacl -RL -m m::rwx /var/www/my_webapp/www
```
But still I can't write to the directory in nextcloud.

**Comment by maniackcrudelis** [comment]
Now, nextcloud should have the permission to write into the directory.
But, as nextcloud could be lazy and capricious, maybe you have to reload the cache, or rescan the files.

**Comment by anmol26s** [comment]
I still did not get write permission. Do I need to add nextcloud to webapp group?

**Comment by maniackcrudelis** [comment]
Well, maybe you can try this too.
But, nextcloud is already suppose to have enough permissions.

Maybe you can also try to remove then readd the mount in nextcloud.

**Comment by anmol26s** [comment]
Ok it works after remounting the drive on nextcloud. But there is other problem now, when any of the file is added to the folder through nextcloud the owner of the content is nextcloud. The app needs to maintain the permission to webapp to run it. Eg. The owner of the /var/www/my_webapp/www/test.txt is nextcloud rather then webapp.

**Comment by maniackcrudelis** [comment]
Of course nextcloud is going to own any new files copied by the interface. That's how unix permissions works.
Here also, you can play with the ACL to give a default permission to webapp to each new file.
But at the end, don't you need to give the permission to the user who run the app you put in the webapp ?

So I think that it would be easier to make a final chown when you have copied all your files.

**Comment by anmol26s** [comment]
If nextcloud is added to webapp `usermod -a -G webapp nextcloud` ,will the webapp maintain the control even if nextcloud is the content owner? 

> But at the end, don't you need to give the permission to the user who run the app you put in the webapp ?

Yes that is the point, for a person who don't know how to use command line and sftp. 

> So I think that it would be easier to make a final chown when you have copied all your files.

The end user feeds content too often. Its not possible to chown every time. Will the cron be good solution?

**Comment by maniackcrudelis** [comment]
Adding nextcloud to the webapp group will not change anything, since the files created by nextcloud will still be owned by nextcloud, not webapp.

So the thing would be to exceed unix permissions by using ACL. Or using unix permission by using the same group.

With ACL permissions, it would be something like that:
```
sudo setfacl -RnL -m d:g:webapp:rwX,g::rwX,o:r-X "DOSSIER"
```
So to give a default write permission to the group webapp.

With unix permissions,
```
sudo usermod -a -G nextcloud webapp
sudo umask 002 "DOSSIER"
```
Means adding webapp to the nextcloud group, so webapp could have the same permission than the nextcloud group. And then set the umask to give to each new file the permission 775. So that the group can write.

**Comment by anmol26s** [comment]
But giving webapp access to nextcloud group, a security breach for all nextcloud data. No?

**Comment by maniackcrudelis** [comment]
Sure, adding webapp to nextcloud group means webapp will have permissions on all nextcloud data

**Comment by anmol26s** [comment]
Ok , I am not sure if the webapp is working when the content is added with nextcloud. I will check for few days and give a feedback.
